Update to Play 2.0-RC3.
Requires new version of specs2. Akka is also upgraded, but sbt
publish-local fails for Akka, though Play still seems to work.

The Akka/sbt error also happens with the old version of Akka. It is:

error] class file needed by package is missing.
[error] reference type Maybe of package xsbti refers to nonexisting symbol.
[error] one error found
[debug] Compilation failed (CompilerInterface)
Compilation failed
       at xsbt.CompilerInterface.run(CompilerInterface.scala:93)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
...